/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdTagsRouteImport } from './routes/projects.$projectId.tags'
import { Route as ProjectsProjectIdStringsRouteImport } from './routes/projects.$projectId.strings'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as ProjectsProjectIdScreensRouteImport } from './routes/projects.$projectId.screens'
import { Route as ProjectsProjectIdReviewsRouteImport } from './routes/projects.$projectId.reviews'
import { Route as ProjectsProjectIdLocalesRouteImport } from './routes/projects.$projectId.locales'
import { Route as ProjectsProjectIdImportRouteImport } from './routes/projects.$projectId.import'
import { Route as ProjectsProjectIdExportRouteImport } from './routes/projects.$projectId.export'
import { Route as ProjectsProjectIdReviewsIndexRouteImport } from './routes/projects.$projectId.reviews.index'
import { Route as ProjectsProjectIdSettingsMembersRouteImport } from './routes/projects.$projectId.settings.members'
import { Route as ProjectsProjectIdSettingsApiTokensRouteImport } from './routes/projects.$projectId.settings.api-tokens'
import { Route as ProjectsProjectIdReviewsChangeSetIdRouteImport } from './routes/projects.$projectId.reviews.$changeSetId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdTagsRoute = ProjectsProjectIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdStringsRoute =
  ProjectsProjectIdStringsRouteImport.update({
    id: '/strings',
    path: '/strings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdScreensRoute =
  ProjectsProjectIdScreensRouteImport.update({
    id: '/screens',
    path: '/screens',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdReviewsRoute =
  ProjectsProjectIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdLocalesRoute =
  ProjectsProjectIdLocalesRouteImport.update({
    id: '/locales',
    path: '/locales',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdImportRoute = ProjectsProjectIdImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdExportRoute = ProjectsProjectIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdReviewsIndexRoute =
  ProjectsProjectIdReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdReviewsRoute,
  } as any)
const ProjectsProjectIdSettingsMembersRoute =
  ProjectsProjectIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)
const ProjectsProjectIdSettingsApiTokensRoute =
  ProjectsProjectIdSettingsApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => ProjectsProjectIdSettingsRoute,
  } as any)
const ProjectsProjectIdReviewsChangeSetIdRoute =
  ProjectsProjectIdReviewsChangeSetIdRouteImport.update({
    id: '/$changeSetId',
    path: '/$changeSetId',
    getParentRoute: () => ProjectsProjectIdReviewsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/import': typeof ProjectsProjectIdImportRoute
  '/projects/$projectId/locales': typeof ProjectsProjectIdLocalesRoute
  '/projects/$projectId/reviews': typeof ProjectsProjectIdReviewsRouteWithChildren
  '/projects/$projectId/screens': typeof ProjectsProjectIdScreensRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteWithChildren
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/reviews/$changeSetId': typeof ProjectsProjectIdReviewsChangeSetIdRoute
  '/projects/$projectId/settings/api-tokens': typeof ProjectsProjectIdSettingsApiTokensRoute
  '/projects/$projectId/settings/members': typeof ProjectsProjectIdSettingsMembersRoute
  '/projects/$projectId/reviews/': typeof ProjectsProjectIdReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/import': typeof ProjectsProjectIdImportRoute
  '/projects/$projectId/locales': typeof ProjectsProjectIdLocalesRoute
  '/projects/$projectId/screens': typeof ProjectsProjectIdScreensRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteWithChildren
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/reviews/$changeSetId': typeof ProjectsProjectIdReviewsChangeSetIdRoute
  '/projects/$projectId/settings/api-tokens': typeof ProjectsProjectIdSettingsApiTokensRoute
  '/projects/$projectId/settings/members': typeof ProjectsProjectIdSettingsMembersRoute
  '/projects/$projectId/reviews': typeof ProjectsProjectIdReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/import': typeof ProjectsProjectIdImportRoute
  '/projects/$projectId/locales': typeof ProjectsProjectIdLocalesRoute
  '/projects/$projectId/reviews': typeof ProjectsProjectIdReviewsRouteWithChildren
  '/projects/$projectId/screens': typeof ProjectsProjectIdScreensRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteWithChildren
  '/projects/$projectId/strings': typeof ProjectsProjectIdStringsRoute
  '/projects/$projectId/tags': typeof ProjectsProjectIdTagsRoute
  '/projects/$projectId/reviews/$changeSetId': typeof ProjectsProjectIdReviewsChangeSetIdRoute
  '/projects/$projectId/settings/api-tokens': typeof ProjectsProjectIdSettingsApiTokensRoute
  '/projects/$projectId/settings/members': typeof ProjectsProjectIdSettingsMembersRoute
  '/projects/$projectId/reviews/': typeof ProjectsProjectIdReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/sign-in'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/export'
    | '/projects/$projectId/import'
    | '/projects/$projectId/locales'
    | '/projects/$projectId/reviews'
    | '/projects/$projectId/screens'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/reviews/$changeSetId'
    | '/projects/$projectId/settings/api-tokens'
    | '/projects/$projectId/settings/members'
    | '/projects/$projectId/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/sign-in'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/export'
    | '/projects/$projectId/import'
    | '/projects/$projectId/locales'
    | '/projects/$projectId/screens'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/reviews/$changeSetId'
    | '/projects/$projectId/settings/api-tokens'
    | '/projects/$projectId/settings/members'
    | '/projects/$projectId/reviews'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/projects'
    | '/sign-in'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/export'
    | '/projects/$projectId/import'
    | '/projects/$projectId/locales'
    | '/projects/$projectId/reviews'
    | '/projects/$projectId/screens'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/strings'
    | '/projects/$projectId/tags'
    | '/projects/$projectId/reviews/$changeSetId'
    | '/projects/$projectId/settings/api-tokens'
    | '/projects/$projectId/settings/members'
    | '/projects/$projectId/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/tags': {
      id: '/projects/$projectId/tags'
      path: '/tags'
      fullPath: '/projects/$projectId/tags'
      preLoaderRoute: typeof ProjectsProjectIdTagsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/strings': {
      id: '/projects/$projectId/strings'
      path: '/strings'
      fullPath: '/projects/$projectId/strings'
      preLoaderRoute: typeof ProjectsProjectIdStringsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/screens': {
      id: '/projects/$projectId/screens'
      path: '/screens'
      fullPath: '/projects/$projectId/screens'
      preLoaderRoute: typeof ProjectsProjectIdScreensRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/reviews': {
      id: '/projects/$projectId/reviews'
      path: '/reviews'
      fullPath: '/projects/$projectId/reviews'
      preLoaderRoute: typeof ProjectsProjectIdReviewsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/locales': {
      id: '/projects/$projectId/locales'
      path: '/locales'
      fullPath: '/projects/$projectId/locales'
      preLoaderRoute: typeof ProjectsProjectIdLocalesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/import': {
      id: '/projects/$projectId/import'
      path: '/import'
      fullPath: '/projects/$projectId/import'
      preLoaderRoute: typeof ProjectsProjectIdImportRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/export': {
      id: '/projects/$projectId/export'
      path: '/export'
      fullPath: '/projects/$projectId/export'
      preLoaderRoute: typeof ProjectsProjectIdExportRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/reviews/': {
      id: '/projects/$projectId/reviews/'
      path: '/'
      fullPath: '/projects/$projectId/reviews/'
      preLoaderRoute: typeof ProjectsProjectIdReviewsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdReviewsRoute
    }
    '/projects/$projectId/settings/members': {
      id: '/projects/$projectId/settings/members'
      path: '/members'
      fullPath: '/projects/$projectId/settings/members'
      preLoaderRoute: typeof ProjectsProjectIdSettingsMembersRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRoute
    }
    '/projects/$projectId/settings/api-tokens': {
      id: '/projects/$projectId/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/projects/$projectId/settings/api-tokens'
      preLoaderRoute: typeof ProjectsProjectIdSettingsApiTokensRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRoute
    }
    '/projects/$projectId/reviews/$changeSetId': {
      id: '/projects/$projectId/reviews/$changeSetId'
      path: '/$changeSetId'
      fullPath: '/projects/$projectId/reviews/$changeSetId'
      preLoaderRoute: typeof ProjectsProjectIdReviewsChangeSetIdRouteImport
      parentRoute: typeof ProjectsProjectIdReviewsRoute
    }
  }
}

interface ProjectsProjectIdReviewsRouteChildren {
  ProjectsProjectIdReviewsChangeSetIdRoute: typeof ProjectsProjectIdReviewsChangeSetIdRoute
  ProjectsProjectIdReviewsIndexRoute: typeof ProjectsProjectIdReviewsIndexRoute
}

const ProjectsProjectIdReviewsRouteChildren: ProjectsProjectIdReviewsRouteChildren =
  {
    ProjectsProjectIdReviewsChangeSetIdRoute:
      ProjectsProjectIdReviewsChangeSetIdRoute,
    ProjectsProjectIdReviewsIndexRoute: ProjectsProjectIdReviewsIndexRoute,
  }

const ProjectsProjectIdReviewsRouteWithChildren =
  ProjectsProjectIdReviewsRoute._addFileChildren(
    ProjectsProjectIdReviewsRouteChildren,
  )

interface ProjectsProjectIdSettingsRouteChildren {
  ProjectsProjectIdSettingsApiTokensRoute: typeof ProjectsProjectIdSettingsApiTokensRoute
  ProjectsProjectIdSettingsMembersRoute: typeof ProjectsProjectIdSettingsMembersRoute
}

const ProjectsProjectIdSettingsRouteChildren: ProjectsProjectIdSettingsRouteChildren =
  {
    ProjectsProjectIdSettingsApiTokensRoute:
      ProjectsProjectIdSettingsApiTokensRoute,
    ProjectsProjectIdSettingsMembersRoute:
      ProjectsProjectIdSettingsMembersRoute,
  }

const ProjectsProjectIdSettingsRouteWithChildren =
  ProjectsProjectIdSettingsRoute._addFileChildren(
    ProjectsProjectIdSettingsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdExportRoute: typeof ProjectsProjectIdExportRoute
  ProjectsProjectIdImportRoute: typeof ProjectsProjectIdImportRoute
  ProjectsProjectIdLocalesRoute: typeof ProjectsProjectIdLocalesRoute
  ProjectsProjectIdReviewsRoute: typeof ProjectsProjectIdReviewsRouteWithChildren
  ProjectsProjectIdScreensRoute: typeof ProjectsProjectIdScreensRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRouteWithChildren
  ProjectsProjectIdStringsRoute: typeof ProjectsProjectIdStringsRoute
  ProjectsProjectIdTagsRoute: typeof ProjectsProjectIdTagsRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdExportRoute: ProjectsProjectIdExportRoute,
  ProjectsProjectIdImportRoute: ProjectsProjectIdImportRoute,
  ProjectsProjectIdLocalesRoute: ProjectsProjectIdLocalesRoute,
  ProjectsProjectIdReviewsRoute: ProjectsProjectIdReviewsRouteWithChildren,
  ProjectsProjectIdScreensRoute: ProjectsProjectIdScreensRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRouteWithChildren,
  ProjectsProjectIdStringsRoute: ProjectsProjectIdStringsRoute,
  ProjectsProjectIdTagsRoute: ProjectsProjectIdTagsRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
